[project]

name = "simpler"

version = "0.1"

# description
readme="README.md"

requires-python = ">=3.7"
# license = {file = "LICENSE.txt"}a

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

